// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DogShowController from "./dog_show_controller.js"
application.register("dog-show", DogShowController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SeeMoreController from "./see_more_controller.js"
application.register("see-more", SeeMoreController)
